export enum ModalType {
  SHOW_MODAL_ACTIONS_MOBILE,
  SHOW_MODAL_RECEIVE_BITCOIN,
  SHOW_MODAL_TRANSACTION_DETAIL,
  SHOW_MODAL_CONFIRM_SEND,
  SHOW_MODAL_CONFIRM_SWAP,
  SHOW_MODAL_PROCESS_TRANSACTION,
  SHOW_MODAL_TRANSACTION_DETAILS,
  SHOW_MODAL_ERROR,
  SHOW_MODAL_CHOOSE_BUY_TOKEN_MOBILE,
  SHOW_MODAL_SELECT_LIST_MOBILE,
}

export type ModalPropsType<T = boolean, P = any> = {
  close: (result?: T) => void;
} & {
  [K in keyof P]: P[K];
};
