name: Deploy Release Preview

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    name: Deploy
    steps:
      - name: logging
        run: echo "${{ github.ref_name }}"
#      - uses: actions/checkout@v2

#      - name: Cache node_modules
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            */*/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

#      - name: Install dependecies
#        run: yarn install --frozen-lockfile

      # set 'steps.vars.outputs.sha_short' variable that is used in 'Build site' step
#      - name: Set short sha output
#        id: vars
#        run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"

#      - name: Build site
#        env:
#          REACT_APP_BASENAME: p2p-wallet-web/release/${{ github.event.release.number }}/
#          REACT_APP_CRYPTO_COMPARE_API_KEY: ${{ secrets.REACT_APP_CRYPTO_COMPARE_API_KEY }}
#          REACT_APP_FEE_RELAYER_URL: ${{ secrets.REACT_APP_FEE_RELAYER_URL }}
#          REACT_APP_SWAP_HOST_FEE_ADDRESS: ${{ secrets.REACT_APP_SWAP_HOST_FEE_ADDRESS }}
#          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
#          REACT_APP_TRANSAK_API_KEY: ${{ secrets.REACT_APP_TRANSAK_API_KEY }}
#          REACT_APP_INTERCOM_APP_ID: ${{ secrets.REACT_APP_INTERCOM_APP_ID }}
#          REACT_APP_MOONPAY_API_KEY: ${{ secrets.REACT_APP_MOONPAY_API_KEY }}
#          REACT_APP_MOONPAY_SIGNER_URL: ${{ secrets.REACT_APP_MOONPAY_SIGNER_URL }}
#          REACT_APP_SENTRY_DSN_ENDPOINT: ${{ secrets.REACT_APP_SENTRY_DSN_ENDPOINT }}
#          REACT_APP_SENTRY_MODE: release
#          REACT_APP_SENTRY_TRACES_SAMPLE_RATE: 1
#          REACT_APP_SENTRY_RELEASE: p2p-wallet-web_release_${{ github.event.release.number }}_${{ steps.vars.outputs.sha_short }}
#        run: yarn build
#
#      - uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: ./packages/web/build
#          clean-exclude: pr-preview/
#          force: false
