name: Deploy Release Preview

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    name: Deploy
    steps:
      - echo: "run"

#      - uses: actions/checkout@v2
#
#      - name: Cache node_modules
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            */*/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
#
#      - name: Install dependecies
#        run: yarn install --frozen-lockfile
#
#      - name: Learn release number
#        uses: rishabhgupta/split-by@v1
#        id: split
#        with:
#          string: ${{ github.ref_name }}
#          split-by: '/'
#
#      - name: Build site
#        env:
#          REACT_APP_BASENAME: p2p-wallet-web/release/${{ steps.split.outputs._1}}/
#          REACT_APP_CRYPTO_COMPARE_API_KEY: ${{ secrets.REACT_APP_CRYPTO_COMPARE_API_KEY }}
#          REACT_APP_FEE_RELAYER_URL: ${{ secrets.REACT_APP_FEE_RELAYER_URL }}
#          REACT_APP_SWAP_HOST_FEE_ADDRESS: ${{ secrets.REACT_APP_SWAP_HOST_FEE_ADDRESS }}
#          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
#          REACT_APP_TRANSAK_API_KEY: ${{ secrets.REACT_APP_TRANSAK_API_KEY }}
#          REACT_APP_INTERCOM_APP_ID: ${{ secrets.REACT_APP_INTERCOM_APP_ID }}
#          REACT_APP_MOONPAY_API_KEY: ${{ secrets.REACT_APP_MOONPAY_API_KEY }}
#          REACT_APP_MOONPAY_SIGNER_URL: ${{ secrets.REACT_APP_MOONPAY_SIGNER_URL }}
#          REACT_APP_SENTRY_DSN_ENDPOINT: ${{ secrets.REACT_APP_SENTRY_DSN_ENDPOINT }}
#          REACT_APP_SENTRY_MODE: release
#          REACT_APP_SENTRY_TRACES_SAMPLE_RATE: 1
#          REACT_APP_SENTRY_RELEASE: p2p-wallet-web_release_${{ steps.split.outputs._1}}
#        run: yarn build
#
#      - uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: ./packages/web/build
#          clean-exclude: release/
#          force: false
#
