name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile

      # set 'steps.vars.outputs.sha_short' variable that is used in 'Build site' step
      - name: Set short sha output
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"

      - name: Build site
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          REACT_APP_BASENAME: ${{ secrets.REACT_APP_BASENAME }}
          REACT_APP_CRYPTO_COMPARE_API_KEY: ${{ secrets.REACT_APP_CRYPTO_COMPARE_API_KEY }}
          REACT_APP_FEE_RELAYER_URL: ${{ secrets.REACT_APP_FEE_RELAYER_URL }}
          REACT_APP_SWAP_HOST_FEE_ADDRESS: ${{ secrets.REACT_APP_SWAP_HOST_FEE_ADDRESS }}
          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
          REACT_APP_TRANSAK_API_KEY: ${{ secrets.REACT_APP_TRANSAK_API_KEY }}
          REACT_APP_INTERCOM_APP_ID: ${{ secrets.REACT_APP_INTERCOM_APP_ID }}
          REACT_APP_MOONPAY_API_KEY: ${{ secrets.REACT_APP_MOONPAY_API_KEY }}
          REACT_APP_MOONPAY_SIGNER_URL: ${{ secrets.REACT_APP_MOONPAY_SIGNER_URL }}
          REACT_APP_SENTRY_DSN_ENDPOINT: ${{ secrets.REACT_APP_SENTRY_DSN_ENDPOINT }}
          REACT_APP_SENTRY_MODE: production
          REACT_APP_SENTRY_TRACES_SAMPLE_RATE: 1
          REACT_APP_SENTRY_RELEASE: p2p-wallet-web_production_${{ steps.vars.outputs.sha_short }}
        run: yarn build

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root # https://github.com/cloudflare/wrangler-action/issues/12#issuecomment-588226602
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
