export enum ModalType {
  SHOW_MODAL_ACTIONS_MOBILE,
  SHOW_MODAL_RECEIVE_BITCOIN,
  SHOW_MODAL_TRANSACTION_CONFIRM,
  SHOW_MODAL_TRANSACTION_DETAILS,
  SHOW_MODAL_TRANSACTION_STATUS,
  SHOW_MODAL_CLOSE_TOKEN_ACCOUNT,
  SHOW_MODAL_ERROR,
  SHOW_MODAL_PROCEED_USERNAME,
  SHOW_MODAL_ADD_COIN,
  SHOW_MODAL_CHOOSE_BUY_TOKEN_MOBILE,
}

export type ModalPropsType<T = boolean, P = any> = {
  close: (result?: T) => void;
} & {
  [K in keyof P]: P[K];
};
